services:
  postgres:
    container_name: ${POSTGRES_CONTAINER_HOST}
    image: postgres:15
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - mr-platform

  relay-server-golang:
    container_name: ${GO_CONTAINER_HOST_RELAY}
    hostname: ${GO_HOST}
    tty: true
    env_file: .env
    build:
      context: .
      dockerfile: ./mr-platform-relay-server/docker/go/Dockerfile
    volumes:
      - ./mr-platform-relay-server/src:/go/src/app
      - ./mr-platform-relay-server/docker/go/log:/go/src/log
    ports:
      - 8084:8000
    networks:
      - mr-platform

  digital-twin-golang:
    container_name: ${GO_CONTAINER_HOST_DIGITAL_TWIN}
    hostname: ${GO_HOST}
    tty: true
    env_file: .env
    build:
      context: .
      dockerfile: ./mr-platform-digital-twin-server/docker/go/Dockerfile
    volumes:
      - ./mr-platform-digital-twin-server/src:/go/src/app
      - ./mr-platform-digital-twin-server/docker/go/log:/go/src/log
    depends_on:
      - "postgres"
    ports:
      - 8087:8000
    networks:
      - mr-platform

  recommend-contents-golang:
    container_name: ${GO_CONTAINER_HOST_RECONTEND}
    hostname: ${GO_HOST}
    tty: true
    env_file: .env
    build:
      context: .
      dockerfile: ./mr-platform-recommend-contents-server/docker/go/Dockerfile
    volumes:
      - ./mr-platform-recommend-contents-server/src:/go/src/app
      - ./mr-platform-recommend-contents-server/docker/go/log:/go/src/log
    depends_on:
      - "postgres"
    ports:
      - 8086:8000
    networks:
      - mr-platform

  contents-golang:
    container_name: ${GO_CONTAINER_HOST_CONTENTS}
    hostname: ${GO_HOST}
    tty: true
    env_file: .env
    build:
      context: .
      dockerfile: ./mr-platform-contents-server/docker/go/Dockerfile
    volumes:
      - ./mr-platform-contents-server/src:/go/src/app
      - ./mr-platform-contents-server/docker/go/log:/go/src/log
    depends_on:
      - "postgres"
    ports:
      - 8089:8000
    networks:
      - mr-platform


networks:
  mr-platform:
    driver: bridge
